spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      client-id: ${spring.application.name}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  liquibase:
    contexts: example-showoff
  servlet:
    multipart:
      max-file-size: 2MB
  application:
    name: task2-rest-api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: 8081
configuration:
  endpoints:
    execution-fact:
      _list:
        max-page-size: 500
kafka:
  topic:
    simpleEmail: simpleEmail
