spring:
  liquibase:
    contexts: example-showoff
  servlet:
    multipart:
      max-file-size: 2MB
  application:
    name: task2-rest-api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

configuration:
  endpoints:
    execution-fact:
      _list:
        max-page-size: 500
